### PR TITLE
jest: Add non-controversial jest lint rules

### PR DESCRIPTION
**Pull request by MrTibbles**
## Changes
- Adds jest plugin
- Adds non-controversial rules

## Notes
I am keen to introduce the [limitation on snapshot sizes](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-large-snapshots.md), however i fear this will result in a few failures on ufc-event-centre. I am a vocal critic of usage snapshots, specifically big ones, as i feel it to be too easy to pass `-u` to simply update a potentially failing snapshot. However introducing a limitation on size of snapshots will make us more conscious of our usage.

### CODE REVIEW

**Comment by parkjh** [comment]
are all the jest rules agreed by the teams?

**Comment by MrTibbles** [comment]
@IMGARENA/imgarena-web-team

**Comment by parkjh** [comment]
> @IMGARENA/imgarena-web-team

vote 👍 yay or 👎 nay?

**Review by johanlajili — DISMISSED** [review]

**Review by renatasva — APPROVED** [review]
👍

**Review by bartek-kisielewicz — APPROVED** [review]

**Review by parkjh — APPROVED** [review]

**Comment by MrTibbles** [comment]
Resolved conflicts

**Review by parkjh — APPROVED** [review]

**Pull request merged**
