### PR TITLE
ts-rules: Disable misguided explicit-function-return-type

### PR DESCRIPTION
**Pull request by MrTibbles**
## Changes
- Disables misguided explicit-function-return-type

### CODE REVIEW

**Comment by johanlajili** [comment]
wow talk about controversial. I seem to recall the enabling of that rule catching a lot of errors in early BTEC. There are occasions where it's a bit annoying but you can disable it specifically then. Where is the want to disable it from?

**Comment by MrTibbles** [comment]
Preferring to lean more on the compiler to infer return types. In honesty i am not 100% sure i am keen on this change, it has been discussed a few times in different teams, so thought i would open the discussion with conviction!

**Comment by johanlajili** [comment]
> Preferring to lean more on the compiler to infer return types. In honesty i am not 100% sure i am keen on this change, it has been discussed a few times in different teams, so thought i would open the discussion with conviction!

it might be that on BTEC specifically, where we don't have strict mode, it's necessary, and client would be okay?
Open to discussion, it is a bit of a pain a rule it's true.

**Comment by parkjh** [comment]
> > Preferring to lean more on the compiler to infer return types. In honesty i am not 100% sure i am keen on this change, it has been discussed a few times in different teams, so thought i would open the discussion with conviction!
> 
> it might be that on BTEC specifically, where we don't have strict mode, it's necessary, and client would be okay?
> Open to discussion, it is a bit of a pain a rule it's true.

question: why is it neccessary for btec to have non strict mode?

**Comment by parkjh** [comment]
> > > > Preferring to lean more on the compiler to infer return types. In honesty i am not 100% sure i am keen on this change, it has been discussed a few times in different teams, so thought i would open the discussion with conviction!
> > > 
> > > 
> > > it might be that on BTEC specifically, where we don't have strict mode, it's necessary, and client would be okay?
> > > Open to discussion, it is a bit of a pain a rule it's true.
> > 
> > 
> > question: why is it neccessary for btec to have non strict mode?
> 
> It's not, it's been on the todo list for ages, but you got like 800 errors to fix to enable it so good luck

challenge accepted

**Comment by alliiiiiii** [comment]
To chip in here, I'm for disabling this rule in the future but as said by others I'd like to get BTEC away from the `any` stuff first.

**Comment by johanlajili** [comment]
> > > > > Preferring to lean more on the compiler to infer return types. In honesty i am not 100% sure i am keen on this change, it has been discussed a few times in different teams, so thought i would open the discussion with conviction!
> > > > 
> > > > 
> > > > it might be that on BTEC specifically, where we don't have strict mode, it's necessary, and client would be okay?
> > > > Open to discussion, it is a bit of a pain a rule it's true.
> > > 
> > > 
> > > question: why is it neccessary for btec to have non strict mode?
> > 
> > 
> > It's not, it's been on the todo list for ages, but you got like 800 errors to fix to enable it so good luck
> 
> challenge accepted

By all mean. Do delete Tennis first before doing that, might help

**Comment by MrTibbles** [comment]
So to summarise are we awaiting a status report on switching to strict on BTEC prior to committing this change? I am in no rush to merge this

**Comment by johanlajili** [comment]
I would say so, in the mean time we can disable that rule in the eslint of other projects (or we can merge that and specify it manually in BTEC eslint)

**Comment by alliiiiiii** [comment]
I tripped over this the other day in BTEC, not a major issue but I'm up for changing this now 👍

**Review by alliiiiiii — APPROVED** [review]

**Comment by johanlajili** [comment]
I think it's now acceptable to merge this.

**Pull request merged**
